---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: backlog-ui-platform
  namespace: homelab-platform
spec:
  encryptedData:
    CF_ACCESS_CLIENT_ID: AgCzXMbDgA9sSub4iqdgVYhT/M2X/JX+UH+45BT4pURiaFd86gAh0Cy4PTWRYSRtrv4XEccC+jPR6tpStfem/tvso4QaRGuyJdvVP9yVJT53hVWPe3VzXN4UwnmikvA2PsosfJi9FH1rfHAwHJjLEofto4g6CwGIzw1/D6lYKhz8mRjXGUaSSpqv4zQp2vDxjKDsjgY8b1Z/wShArGIHnu3/C+4oLbab2bcCXTHYF2tRwxDqmbsFe5GciLdCpAl4j2bl+PPPxRdbvm37agQV2Jk+Nn7I2Di5XfoaM+PJNH51GQbvJCoHSVV4d3Y5ADUf2AMadSL6r//yPNtV6CMPoMcMtEiaeRR235dLW974LGsz5VkkAPDQkTgIm/TeYP5J+T5UP1ja9tsqmDnk8vdIkMzyYHQSzw0HSgYp++lZlroYeXGOzMBImBmZLWA/1zu+GZDTkyOvai6ZYQ0eGz4DlPJqvk0AvCefnU+PwhhDynMSsJWi4dlz/ZtixE9h027/ZwOvT5SU59DQ+G9DwsrB9WbAGSD8t4feXU1a0IK5sLZleqt6YDAACfX6q1+rnmvwcF6NC6mHsvH4joV7iOCfQLrBCKBhE9Y244FzzU0gjRNTnYnoE1kqrY9V2m76Wsb15SwnOt2Xd8LWG2PNl3/jXdJ9BOJ0MkLDXqpgbw5iPWIERTDDZ1REdEJqgNwmQeXLaF9uGXPLJUUhYPzPIKON+p50hW0Zsdf+2EB2m8ZSC/w1tDTRjfFm06w=
    CF_ACCESS_CLIENT_SECRET: AgBJ4k++t4IoA0rzdnwW/jUBy6NxOlRb+Zg1hWp3ih6H32W6RbRrnQDK2q6E/+x7EtqGAn1+P9UsjkS04NNsjl9AKBsGqFsVDGKFKtZ/Ftw2+bBvWSLsx5Hb+zpn0Ae+nD9JmJhh6et7u7Zc1Zc3njW7GbVqdVW2Ke1AM8oRk/ddUXnL9zX5y/pNIyGWJT7FtsyYSkMmCpwa2zeHHsWVonAmFC8B0Nu7ZJRc4KRFggO08bzJ63Wjis46y4A9A7A29XZa9MlUew/ypLFSjoppA/2C5l2enlXt+OBdOCGLiyHqeG+wJWy0IiPJI65EMTXNnahFNQFN7njRNn3TIYs4n/kfP2EXobTbXLEBZynSn/DO69Wi5sXDRMTUT9zPWg+hvY+XifNRrqoyfysVR5xQGQ1JMQzoozld1m0aFU03AceMAJNrg6ERXIBLgoS5o2rT/ahtAH7FVr1pHLmjeboDfhYcPQnnsxRcF9NaFtRq8PVhWDiGXb/RetUfDJsaEzykk0UDFjrG7ur9NtqgQJXBoaMNbwqCI3QopBmvffCNVuvWxRXigmIM01HRiQkXCR5iEF5FrLEZZxTY3UzEIh/zjxhFIkH1vDBSo/H3IdXs8k4iRyBQ/K3//jeLUrIE6mSBMIoFbMG0z9nIauPCWhBAnVZWNd5VHdywZSCLnqLLSqUv3EEXI0hvi5sZ5M49FoyriMdvjon7YYxyT6kmzjNZeY95frkmt9yilqUBt6Qg/DzQhkwjJpKcthcKI4uoEsphQmn6dXrhdiQlEF2FNfWu3mkx
  template:
    metadata:
      name: backlog-ui-platform
      namespace: homelab-platform
    type: Opaque
