apiVersion: v1
kind: Service
metadata:
  name: backlog-ui
  namespace: homelab-platform
  labels:
    app.kubernetes.io/name: backlog-ui
    app.kubernetes.io/part-of: homelab-platform
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: backlog-ui
  ports:
    - name: https
      port: 3001
      targetPort: https
